apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  databaseUrl: {{ .Values.databaseDetails.databaseURL | b64enc }}
  databasePort: {{ .Values.databaseDetails.databasePort | replace ":" "" | b64enc }}
  databaseName: {{ .Values.databaseDetails.databaseName | b64enc }}
  username: {{ .Values.databaseDetails.username | b64enc }}
  password: {{ .Values.databaseDetails.password | b64enc }}
