apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.buildArtifactoryCreds }}
kind: Secret
metadata:
  name: build-artifactory-creds
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson